language: java
jdk:
  - oraclejdk7
install:
  - mvn clean test verify -Ptravis-ci

notifications:
  email:
     - stas-martynov-98@mail.ru

services:
  - RenderSymbols
  
after_success:
  - coveralls
