language: java
jdk:
  - oraclejdk7
before_install: cd src
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - mvn cobertura:cobertura coveralls:report -Ptravis-ci


notifications:
  email:
     - stas-martynov-98@mail.ru

services:
  - RenderSymbols
